version: '3'

services:
  proxy:
    container_name: nginx
    hostname: fb-proxy.test
    image: nginx
    ports:
      - 443:443
    volumes:
      - /fblx/nginx/conf:/etc/nginx
      - /fblx/nginx/cert:/etc/ssl/private

  authentication:
    build: ./authSrv
    container_name: authSrv
    hostname: authSrv.test 
    ports: 
      - "7000"
    volumes:
      - /fblx/authSrv:/usr/src/app

  api:
    build: ./mockApi
    container_name: api
    hostname: mockApi.test
    ports: 
      - "8000"
    volumes:
      - /fblx/mockApi:/usr/src/app

  redis:
     build: ./redis
     container_name: redis
     hostname: redis.test
     command: ./redis-server /redis_data/redis.conf
     ports:
       - "6379"
     volumes:
       - /fblx/redis/data:/redis_data

    #elastic service:
    #parser service:
