version: '3'

services:
  proxy:
    container_name: nginx
    hostname: fb-proxy.test
    image: nginx
    ports:
      - 443:443
    volumes:
      - /fblx/nginx/conf:/etc/nginx
      - /fblx/nginx/cert:/etc/ssl/private

  authentication:
    build: ./authSrv
    container_name: authSrv
    hostname: authSrv.test 
    ports: 
      - "7000"
    volumes:
      - /fblx/authSrv:/usr/src/app

  api:
    build: ./mockApi
    container_name: api
    hostname: mockApi.test
    ports: 
      - "8000"
    volumes:
      - /fblx/mockApi:/usr/src/app

  redis:
     container_name: redis
     hostname: redis.test
     image: redis
     ports:
             - "6379:6379"
     volumes:
       - /fblx/redis/data:/data
     entrypoint: redis-server /data/redis.conf



    #elastic service:
    #parser service:
